name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "next.config.ts"
      - "tailwind.config.ts"
      - "postcss.config.mjs"
      - ".github/workflows/**"
      - "eslint.config.mjs"
      - "tsconfig.json"
    paths-ignore:
      - "renovate.json"
      - "**/*.md"
      - ".vscode/**"
      - "context/**"

env:
  NODE_VERSION: "22.14.0"
  PNPM_VERSION: "10.5.2"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - run: pnpm run lint
        env:
          DEBUG_URL: ${{ secrets.TEST_DEBUG_URL }}

  format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - run: pnpm run format

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - run: pnpm run typecheck

  build:
    needs: [lint, format, typecheck]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - name: Build static site
        run: pnpm run build
        env:
          DEBUG_URL: ${{ secrets.TEST_DEBUG_URL }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: out/
          retention-days: 7
