name: Renovate Config Validator

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "renovate.json"
      - ".github/workflows/renovate-config-validator-ci.yml"

jobs:
  renovate-config-validator:
    timeout-minutes: 10
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: validate renovate.json
        run: npx --package=renovate -c renovate-config-validator
